# Generated by Django 4.0.3 on 2022-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_da_receita',
            field=models.ImageField(blank=True, upload_to='foto/%d/%m/%Y'),
        ),
    ]
